workflows:
expo-ios:
  name: Expo iOS Build

  environment:
    node: 20

  scripts:
    - name: Install dependencies
      script: |
        npm install

    - name: Install Expo tools
      script: |
        npm install -g eas-cli

    - name: Generate iOS files
      script: |
        npx expo prebuild --platform ios

  artifacts:
    - ios/**