kind = "mobile"
previewPath = "/"
title = "SimpleBooking"
version = "1.0.0"
id = "artifacts/simple-booking"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22252

[services.development]
run = "pnpm --filter @workspace/simple-booking run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/simple-booking", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/simple-booking", "run", "serve" ]

[services.env]
PORT = "22252"
BASE_PATH = "/"
